version: "3.9"
services:
  jwcapi:
    build: .
    restart: always
    labels:
      - traefik.http.routers.admin.rule=Host(`api.jwcindia.com`)
      - traefik.http.routers.admin.tls=true
      - traefik.http.routers.admin.tls.certresolver=lets-encrypt
      - traefik.port=8002
    networks:
      - internal
      - web
    ports:
      - "8002:8002"
networks:
  web:
    external: true
  internal:
    external: false
