version: "3.9"
services:
  jwcapi:
    build: .
    restart: always
    labels:
      - traefik.frontend.rule=Host:api.jwcindia.com
    networks:
      - internal
      - web
    ports:
      - "8002:8002"
networks:
  web:
    external: true
  internal:
    external: false
